
OpenLayers.Util.extend(OpenLayers.Lang.fr, {
    "Various OSM map" : "Diverses cartes OSM",
    "Mapnik" : "Mapnik",
    "White background" : "Fond blanc",
    "Black background" : "Fond Noir",
    "TopoMap" : "Carte d'altitude",
    "Osmarender" : "Osmarender",
    "OpenCycleMap" : "OpenCycleMap",
    "OpenPisteMap" : "OpenPisteMap",
    "Public transport" : "Transports publics",
    "CloudMade nonames" : "CloudMade sans nom",
    "September 2008" : "Septembre 2008",
    "June 2009" : "Juin 2009",
    "June 2010" : "Juin 2010",
    "Contours" : "Contours",
    "Speed" : "Vitesse",
    "Weight" : "Poids",
    "Height" : "Hauteur",
    "Width" : "Largeur",
    "Length" : "Longueur",
    "Hiking (Ways)" : "Excursion (chemin)",
    "Hiking (Nodes)" : "Excursion (POI)",
    "MTB" : "MTB",
    "Sled" : "Luge",
    "Snows shoe" : "Raquette",
    "Nordic" : "Ski de fond",
    "Down hill" : "Ski de piste",
    "Winter Walks" : "Promenades hivernales",
    "Fitness trail" : "Parcours santé / PisteVita",
    "Text of fixme and note" : "A fixer et notes",
    "Duplicates nodes" : "Noeud dupliquer",
    "Hiking Tails" : "Parcours santé / PisteVita",
    "All features" : "Toutes les fonctionnalités",
    "Raw" : "Brut",
    "Permalink" : "Permalien",
    "Edit with JOSM" : "Éditer avec JOSM",
    "Base Layers" : "Couches de base",
    "Dem" : "Altitude",
    "Outdoor" : "Sports extérieurs",
    "Utils" : "Utiles",
    "Debug" : "Debug",
    "Swiss history" : "Suisse historique",
    "Other" : "Autre",
    "Nodes" : "Nœuds",
    "Ways" : "Chemins",
    "Relations" : "Relations",
    "Layers" : "Couche",
    "Selected feature" : "Données sélectionnées",
    "Edit on Potlatch" : "Éditer avec Potlatch",
    "Utilities links" : "Liens utiles",
    "Amenity (POI) Editor" : "Amenity (POI) Editor",
    "Keep right!" : "Keep right!",
    "Restrictions" : "Restrictions",
    "Max speed" : "Vitesse Maximales",
    "Refuges.info" : "Refuges.info",
    "OSBrowser" : "OSBrowser",
    "Other test site" : "Autre Site de test",
    "Credits" : "Crédits",
    "Info" : "Informations"
});
