function getJOSMLikeStyleMap() {
    var styleMap = new OpenLayers.StyleMap();
    addPoint(styleMap, 'oneway', '.+', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'bridge', '.+', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'tunnel', '.+', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'tunnel', '.+', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'cutting', '.+', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'embankment', '.+', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'barrier', 'hedge', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'barrier', 'wall', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'barrier', 'city_wall', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'barrier', 'retaining_wall', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'motorway', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'motorway_link', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'trunk', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'trunk_link', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'primary', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'primary_link', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'secondary', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'secondary_link', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'tertiary', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'unclassified', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'road', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'unsurfaced', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'track', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'residential', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'living_street', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'service', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'bridleway', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'cycleway', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'footway', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'path', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'pedestrian', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'highway', 'bus_guideway', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'junction', 'roundabout', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'cycleway', 'lane', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'cycleway', 'opposite_lane', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'cycleway', 'track', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'cycleway', 'opposite_track', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'cycleway', 'opposite', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'tracktype', 'grade1', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'tracktype', 'grade2', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'tracktype', 'grade3', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'tracktype', 'grade4', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'tracktype', 'grade5', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'waterway', 'river', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'waterway', 'riverbank', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'waterway', 'canal', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'waterway', 'stream', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'waterway', 'ditch', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'waterway', 'drain', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'railway', 'rail', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'railway', 'tram', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'railway', 'light_rail', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'railway', 'subway', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'railway', 'preserved', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'railway', 'disused', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'railway', 'abandoned', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'railway', 'narrow_gauge', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'railway', 'monorail', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'railway', 'platform', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'railway', 'funicular', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'service', 'yard', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'service', 'siding', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'service', 'spur', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'power', 'line', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'power', 'minor_line', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'man_made', 'pipeline', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'route', 'bus', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'route', 'ferry', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'route', 'flight', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'route', 'ncn', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'route', 'subsea', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'route', 'ski', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'route', 'tour', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'route', 'pub_crawl', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'boundary', 'national', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'boundary', 'administrative', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'boundary', 'civil', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'boundary', 'political', 'josm/misc/deprecated.png');
    addPoint(styleMap, 'boundary', 'national_park', 'josm/misc/deprecated.png');

    addPoint(styleMap, 'fixme', '.+', 'josm/fixme.png');
    addPoint(styleMap, 'FIXME', '.+', 'josm/fixme.png');

    addPoint(styleMap, 'restriction', 'no_left_turn', 'josm/vehicle/restriction/turn_restrictions/no_left_turn.png');
    addPoint(styleMap, 'restriction', 'no_right_turn', 'josm/vehicle/restriction/turn_restrictions/no_right_turn.png');
    addPoint(styleMap, 'restriction', 'no_straight_on', 'josm/vehicle/restriction/turn_restrictions/no_straight_on.png');
    addPoint(styleMap, 'restriction', 'no_u_turn', 'josm/vehicle/restriction/turn_restrictions/no_u_turn.png');
    addPoint(styleMap, 'restriction', 'only_left_turn', 'josm/vehicle/restriction/turn_restrictions/only_left_turn.png');
    addPoint(styleMap, 'restriction', 'only_right_turn', 'josm/vehicle/restriction/turn_restrictions/only_right_turn.png');
    addPoint(styleMap, 'restriction', 'only_straight_on', 'josm/vehicle/restriction/turn_restrictions/only_straight_on.png');
    addPoint(styleMap, 'bridge', '.+', 'josm/vehicle/viaduct.png');
    addStroke(styleMap, 'bridge', '.+', '#ff0000', 2, 'dash');
    addPoint(styleMap, 'bridge', 'viaduct', 'josm/vehicle/viaduct.png');
    addPoint(styleMap, 'bridge', 'aqueduct', 'josm/nautical/aqueduct.png');
    addPoint(styleMap, 'bridge', 'swing', 'josm/vehicle/viaduct.png');
    addStroke(styleMap, 'tunnel', '.+', '#ff0000', 2, 'dash');
    addStroke(styleMap, 'cutting', '.+', '#ff0000', 2, 'dash');
    addStroke(styleMap, 'embankment', '.+', '#ff0000', 2, 'dash');
    addPoint(styleMap, 'access', '.+', 'josm/vehicle/restriction/access.png');
    addPoint(styleMap, 'access', 'permissive', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'access', 'private', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'access', 'destination', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'bicycle', '.+', 'josm/vehicle/restriction/bicycle.png');
    addPoint(styleMap, 'bicycle', 'designated', 'josm/vehicle/restriction/bicycle-designated.png');
    addPoint(styleMap, 'foot', '.+', 'josm/vehicle/restriction/foot.png');
    addPoint(styleMap, 'foot', 'designated', 'josm/vehicle/restriction/foot-designated.png');
    addPoint(styleMap, 'goods', '.+', 'josm/vehicle/restriction/goods.png');
    addPoint(styleMap, 'hgv', '.+', 'josm/vehicle/restriction/goods.png');
    addPoint(styleMap, 'horse', '.+', 'josm/vehicle/restriction/horse.png');
    addPoint(styleMap, 'horse', 'designated', 'josm/vehicle/restriction/horse-designated.png');
    addPoint(styleMap, 'motorcycle', '.+', 'josm/vehicle/restriction/motorbike.png');
    addPoint(styleMap, 'motorcar', '.+', 'josm/vehicle/restriction/motorcar.png');
    addPoint(styleMap, 'psv', '.+', 'josm/vehicle/restriction/psv.png');
    addPoint(styleMap, 'motorboat', '.+', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'boat', '.+', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'noexit', '.+', 'josm/vehicle/restriction/dead_end.png');
    addPoint(styleMap, 'maxweight', '.+', 'josm/vehicle/restriction/maxweight.png');
    addPoint(styleMap, 'maxheight', '.+', 'josm/vehicle/restriction/maxheight.png');
    addPoint(styleMap, 'maxwidth', '.+', 'josm/vehicle/restriction/maxwidth.png');
    addPoint(styleMap, 'maxlength', '.+', 'josm/vehicle/restriction/maxlength.png');
    addPoint(styleMap, 'maxspeed', '.+', 'josm/vehicle/restriction/speed.png');
    addPoint(styleMap, 'minspeed', '.+', 'josm/vehicle/restriction/minspeed.png');
    addPoint(styleMap, 'maxstay', '.+', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'toll', '.+', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'barrier', '.+', 'josm/vehicle/restriction/barrier.png');
    addPoint(styleMap, 'barrier', 'bollard', 'josm/vehicle/restriction/bollard.png');
    addStroke(styleMap, 'barrier', 'bollard', '#F0F050', 3, 'dash');
    addPoint(styleMap, 'barrier', 'gate', 'josm/vehicle/gate.png');
    addStrokeArea(styleMap, 'barrier', 'hedge', '#F0F050', '3');
    addPoint(styleMap, 'barrier', 'stile', 'josm/vehicle/stile.png');
    addPoint(styleMap, 'barrier', 'turnstile', 'josm/vehicle/turnstile.png');
    addPoint(styleMap, 'barrier', 'fence', 'josm/misc/no_icon.png');
    addStrokeArea(styleMap, 'barrier', 'fence', '#F0F050', '3');
    addPoint(styleMap, 'barrier', 'cycle_barrier', 'josm/vehicle/cycle_barrier.png');
    addPoint(styleMap, 'barrier', 'lift_gate', 'josm/vehicle/lift_gate.png');
    addStrokeArea(styleMap, 'barrier', 'wall', '#F0F050', '3');
    addPoint(styleMap, 'barrier', 'toll_booth', 'josm/vehicle/toll_booth.png');
    addArea(styleMap, 'barrier', 'toll_booth', '#F0F050');
    addPoint(styleMap, 'barrier', 'kissing_gate', 'josm/misc/no_icon.png');
    addStrokeArea(styleMap, 'barrier', 'city_wall', '#F0F050', '3');
    addPoint(styleMap, 'barrier', 'entrance', 'josm/vehicle/entrance.png');
    addStrokeArea(styleMap, 'barrier', 'retaining_wall', '#F0F050', '3');
    addPoint(styleMap, 'barrier', 'cattle_grid', 'josm/vehicle/cattle_grid.png');
    addPoint(styleMap, 'barrier', 'block', 'josm/misc/no_icon.png');
    addStrokeArea(styleMap, 'barrier', 'block', '#F0F050', '3');
    addPoint(styleMap, 'barrier', 'border_control', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'barrier', 'bump_gate', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'barrier', 'sally_port', 'josm/vehicle/sally_port.png');
    addPoint(styleMap, 'barrier', 'portcullis', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'barrier', 'spikes', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'barrier', 'bus_trap', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'barrier', 'drawbridge', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'barrier', 'hampshire_gate', 'josm/misc/no_icon.png');
    addStroke(styleMap, 'highway', 'motorway', '#809bc0', 3);
    addStroke(styleMap, 'highway', 'motorway_link', '#809bc0', 3);
    addStroke(styleMap, 'highway', 'trunk', '#7fc97f', 3);
    addStroke(styleMap, 'highway', 'trunk_link', '#7fc97f', 3);
    addStroke(styleMap, 'highway', 'primary', '#fb805f', 3);
    addStroke(styleMap, 'highway', 'primary_link', '#fb805f', 3);
    addStroke(styleMap, 'highway', 'secondary', '#fdbf6f', 3);
    addStroke(styleMap, 'highway', 'secondary_link', '#fdbf6f', 3);
    addStroke(styleMap, 'highway', 'tertiary', '#f7f496', 2);
    addStroke(styleMap, 'highway', 'unclassified', '#c0c0c0', 2);
    addStroke(styleMap, 'highway', 'road', '#ff0000', 2, 'dash');
    addStroke(styleMap, 'highway', 'unsurfaced', '#c0c0c0', 1);
    addStroke(styleMap, 'highway', 'track', '#006600', 1);
    addStroke(styleMap, 'highway', 'residential', '#c0c0c0', 2);
    addStroke(styleMap, 'highway', 'living_street', '#c0c0c0', 2, 'dash');
    addStroke(styleMap, 'highway', 'service', '#809bc0', 1);
    addStroke(styleMap, 'highway', 'bridleway', '#c08000', 1);
    addStroke(styleMap, 'highway', 'cycleway', '#b100ff', 1);
    addStroke(styleMap, 'highway', 'footway', '#00ff00', 1);
    addStroke(styleMap, 'highway', 'path', '#00ff00', 1, 'dash');
    addStroke(styleMap, 'highway', 'path', '#b100ff', 1);
    addStroke(styleMap, 'highway', 'path', '#b100ff', 1);
    addStroke(styleMap, 'highway', 'path', '#00ff00', 1);
    addStroke(styleMap, 'highway', 'path', '#00ff00', 1);
    addStroke(styleMap, 'highway', 'path', '#b100ff', 1, 'dash');
    addStroke(styleMap, 'highway', 'path', '#b100ff', 1, 'dash');
    addStrokeArea(styleMap, 'highway', 'pedestrian', '#00ff00', '3');
    addPoint(styleMap, 'highway', 'steps', 'josm/transport/steps.png');
    addStroke(styleMap, 'highway', 'steps', '#00ff00', 1, 'dash');
    addStroke(styleMap, 'highway', 'bus_guideway', '#404040', 1, 'dash');
    addPoint(styleMap, 'direction', 'clockwise', 'josm/vehicle/restriction/roundabout_left.png');
    addPoint(styleMap, 'highway', 'mini_roundabout', 'josm/vehicle/restriction/roundabout_right.png');
    addPoint(styleMap, 'highway', 'stop', 'josm/vehicle/restriction/stop.png');
    addPoint(styleMap, 'highway', 'traffic_signals', 'josm/vehicle/restriction/traffic-light.png');
    addPoint(styleMap, 'highway', 'street_lamp', 'josm/misc/streetlamp.png');
    addPoint(styleMap, 'highway', 'speed_camera', 'josm/vehicle/restriction/speed_trap.png');
    addPoint(styleMap, 'traffic_sign', 'city_limit', 'josm/vehicle/restriction/citylimit.png');
    addPoint(styleMap, 'highway', 'crossing', 'josm/vehicle/zebra_crossing.png');
    addPoint(styleMap, 'highway', 'incline', 'josm/vehicle/restriction/incline.png');
    addPoint(styleMap, 'highway', 'incline_steep', 'josm/vehicle/restriction/incline.png');
    addPoint(styleMap, 'highway', 'motorway_junction', 'josm/vehicle/exit.png');
    addPoint(styleMap, 'highway', 'services', 'josm/vehicle/services.png');
    addArea(styleMap, 'highway', 'services', '#c0c0c0');
    addPoint(styleMap, 'highway', 'ford', 'josm/vehicle/ford.png');
    addStroke(styleMap, 'highway', 'ford', '#ff0000', 2);
    addPoint(styleMap, 'highway', 'bus_stop', 'josm/transport/bus_small.png');
    addPoint(styleMap, 'highway', 'turning_circle', 'josm/vehicle/turning_circle.png');
    addArea(styleMap, 'highway', 'turning_circle', '#c0c0c0');
    addPoint(styleMap, 'highway', 'passing_place', 'josm/vehicle/passing_place.png');
    addPoint(styleMap, 'highway', 'construction', 'josm/misc/construction.png');
    addStroke(styleMap, 'highway', 'construction', '#ffff00', 2, 'dash');
    addPoint(styleMap, 'highway', 'emergency_access_point', 'josm/service/emergency_access_point.png');
    addArea(styleMap, 'highway', 'emergency_access_point', '#c0c0c0');
    addArea(styleMap, 'junction', 'roundabout', '#eeeeee');
    addStroke(styleMap, 'tracktype', 'grade1', '#006600', 1, 'dash');
    addStroke(styleMap, 'tracktype', 'grade2', '#006600', 1, 'dash');
    addStroke(styleMap, 'tracktype', 'grade3', '#006600', 1, 'dash');
    addStroke(styleMap, 'tracktype', 'grade4', '#006600', 1, 'dash');
    addStroke(styleMap, 'tracktype', 'grade5', '#006600', 1, 'dash');
    addStroke(styleMap, 'waterway', 'river', '#0000ff', 2);
    addStrokeArea(styleMap, 'waterway', 'riverbank', '#0000cf', '1');
    addStroke(styleMap, 'waterway', 'canal', '#0000ff', 2);
    addStroke(styleMap, 'waterway', 'stream', '#6600cc', 1);
    addStroke(styleMap, 'waterway', 'ditch', '#0000ff', 1);
    addStroke(styleMap, 'waterway', 'drain', '#0000ff', 1);
    addPoint(styleMap, 'waterway', 'dock', 'josm/nautical/boatyard.png');
    addArea(styleMap, 'waterway', 'dock', '#0000cf');
    addPoint(styleMap, 'waterway', 'lock_gate', 'josm/nautical/lock_gate.png');
    addPoint(styleMap, 'waterway', 'turning_point', 'josm/nautical/turning.png');
    addPoint(styleMap, 'waterway', 'boatyard', 'josm/nautical/boatyard.png');
    addArea(styleMap, 'waterway', 'boatyard', '#d8d8d8');
    addPoint(styleMap, 'waterway', 'water_point', 'josm/accommodation/camping/water.png');
    addPoint(styleMap, 'waterway', 'waste_disposal', 'josm/accommodation/camping/wastewater.png');
    addPoint(styleMap, 'waterway', 'mooring', 'josm/nautical/marina.png');
    addPoint(styleMap, 'waterway', 'weir', 'josm/nautical/weir.png');
    addStroke(styleMap, 'waterway', 'weir', '#d8d8d8', 2);
    addPoint(styleMap, 'waterway', 'rapids', 'josm/misc/no_icon.png');
    addStroke(styleMap, 'waterway', 'rapids', '#8080ff', 2);
    addPoint(styleMap, 'waterway', 'dam', 'josm/misc/no_icon.png');
    addStrokeArea(styleMap, 'waterway', 'dam', '#d8d8d8', '2');
    addPoint(styleMap, 'waterway', 'waterfall', 'josm/nautical/waterfall.png');
    addStroke(styleMap, 'waterway', 'waterfall', '#d8d8d8', 2);
    addPoint(styleMap, 'railway', 'station', 'josm/transport/railway_station.png');
    addArea(styleMap, 'railway', 'station', '#f7efb7');
    addPoint(styleMap, 'railway', 'halt', 'josm/transport/railway_small.png');
    addPoint(styleMap, 'railway', 'tram_station', 'josm/transport/railway_station.png');
    addArea(styleMap, 'railway', 'tram_station', '#f7efb7');
    addPoint(styleMap, 'railway', 'tram_stop', 'josm/transport/railway_small.png');
    addPoint(styleMap, 'railway', 'subway_entrance', 'josm/transport/underground.png');
    addArea(styleMap, 'railway', 'subway_entrance', '#f7efb7');
    addPoint(styleMap, 'railway', 'crossing', 'josm/vehicle/crossing_small.png');
    addArea(styleMap, 'railway', 'crossing', '#f7efb7');
    addPoint(styleMap, 'railway', 'level_crossing', 'josm/vehicle/crossing.png');
    addArea(styleMap, 'railway', 'level_crossing', '#f7efb7');
    addStroke(styleMap, 'railway', 'rail', '#404040', 2, 'dash');
    addStroke(styleMap, 'railway', 'tram', '#808080', 1, 'dash');
    addStroke(styleMap, 'railway', 'light_rail', '#808080', 2, 'dash');
    addStroke(styleMap, 'railway', 'subway', '#606060', 1, 'dash');
    addStroke(styleMap, 'railway', 'preserved', '#404040', 1, 'dash');
    addStroke(styleMap, 'railway', 'disused', '#404040', 1, 'dash');
    addStroke(styleMap, 'railway', 'abandoned', '#404040', 1, 'dash');
    addStroke(styleMap, 'railway', 'narrow_gauge', '#404040', 1, 'dash');
    addStroke(styleMap, 'railway', 'monorail', '#404040', 1, 'dash');
    addPoint(styleMap, 'railway', 'turntable', 'josm/transport/turntable.png');
    addArea(styleMap, 'railway', 'turntable', '#404040');
    addPoint(styleMap, 'railway', 'buffer_stop', 'josm/transport/buffer_stop.png');
    addArea(styleMap, 'railway', 'buffer_stop', '#404040');
    addStrokeArea(styleMap, 'railway', 'platform', '#404040', '2');
    addStroke(styleMap, 'railway', 'funicular', '#404040', 1, 'dash');
    addPoint(styleMap, 'aeroway', 'aerodrome', 'josm/transport/airport.png');
    addStrokeArea(styleMap, 'aeroway', 'aerodrome', '#660000', '2');
    addPoint(styleMap, 'aeroway', 'terminal', 'josm/transport/airport/terminal.png');
    addArea(styleMap, 'aeroway', 'terminal', '#bb0000');
    addPoint(styleMap, 'aeroway', 'helipad', 'josm/transport/airport/helipad.png');
    addArea(styleMap, 'aeroway', 'helipad', '#330000');
    addPoint(styleMap, 'aeroway', 'runway', 'josm/transport/airport.png');
    addStroke(styleMap, 'aeroway', 'runway', '#330000', 3);
    addPoint(styleMap, 'aeroway', 'taxiway', 'josm/transport/airport.png');
    addStroke(styleMap, 'aeroway', 'taxiway', '#660000', 2);
    addPoint(styleMap, 'aeroway', 'apron', 'josm/transport/airport.png');
    addArea(styleMap, 'aeroway', 'apron', '#990000');
    addPoint(styleMap, 'aeroway', 'gate', 'josm/transport/airport/terminal.png');
    addPoint(styleMap, 'aeroway', 'windsock', 'josm/transport/airport/windsock.png');
    addPoint(styleMap, 'aerialway', 'cable_car', 'josm/transport/aerialway/cable_car.png');
    addStroke(styleMap, 'aerialway', 'cable_car', '#663300', 1, 'dash');
    addPoint(styleMap, 'aerialway', 'gondola', 'josm/transport/aerialway/cable_car.png');
    addStroke(styleMap, 'aerialway', 'gondola', '#663300', 1, 'dash');
    addPoint(styleMap, 'aerialway', 'chair_lift', 'josm/transport/aerialway/chair_lift.png');
    addStroke(styleMap, 'aerialway', 'chair_lift', '#663300', 1, 'dash');
    addPoint(styleMap, 'aerialway', 'drag_lift', 'josm/transport/aerialway/drag_lift.png');
    addStroke(styleMap, 'aerialway', 'drag_lift', '#663300', 1, 'dash');
    addPoint(styleMap, 'aerialway', 'station', 'josm/transport/aerialway/station.png');
    addArea(styleMap, 'aerialway', 'station', '#663300');
    addPoint(styleMap, 'aerialway', 'pylon', 'josm/misc/no_icon.png');
    addArea(styleMap, 'aerialway', 'pylon', '#663300');
    addPoint(styleMap, 'piste:difficulty', 'easy', 'josm/sport/skiing.png');
    addStrokeArea(styleMap, 'piste:difficulty', 'easy', '#0000ff', '6');
    addPoint(styleMap, 'piste:difficulty', 'intermediate', 'josm/sport/skiing.png');
    addStrokeArea(styleMap, 'piste:difficulty', 'intermediate', '#ff0000', '6');
    addPoint(styleMap, 'piste:difficulty', 'advanced', 'josm/sport/skiing.png');
    addStrokeArea(styleMap, 'piste:difficulty', 'advanced', '#606060', '6');
    addPoint(styleMap, 'piste:difficulty', 'expert', 'josm/sport/skiing.png');
    addStrokeArea(styleMap, 'piste:difficulty', 'expert', '#606060', '6');
    addPoint(styleMap, 'piste:difficulty', 'freeride', 'josm/sport/skiing.png');
    addStrokeArea(styleMap, 'piste:difficulty', 'freeride', '#ffff00', '6');
    addPoint(styleMap, 'piste:difficulty', 'novice', 'josm/sport/skiing.png');
    addStrokeArea(styleMap, 'piste:difficulty', 'novice', '#00ff00', '6');
    addPoint(styleMap, 'power', 'tower', 'josm/misc/landmark/power/tower_small.png');
    addArea(styleMap, 'power', 'tower', '#eeeeee');
    addPoint(styleMap, 'power', 'pole', 'josm/misc/landmark/power/pole.png');
    addStroke(styleMap, 'power', 'line', '#eeeeee', 1);
    addStroke(styleMap, 'power', 'minor_line', '#eeeeee', 1);
    addPoint(styleMap, 'power', 'station', 'josm/misc/landmark/power.png');
    addArea(styleMap, 'power', 'station', '#eeeeee');
    addPoint(styleMap, 'power', 'sub_station', 'josm/misc/landmark/power.png');
    addArea(styleMap, 'power', 'sub_station', '#eeeeee');
    addPoint(styleMap, 'power_source', 'wind', 'josm/misc/landmark/power/wind.png');
    addArea(styleMap, 'power_source', 'wind', '#eeeeee');
    addPoint(styleMap, 'power_source', 'hydro', 'josm/misc/landmark/power/hydro.png');
    addArea(styleMap, 'power_source', 'hydro', '#eeeeee');
    addPoint(styleMap, 'power_source', 'fossil', 'josm/misc/landmark/power/fossil.png');
    addArea(styleMap, 'power_source', 'fossil', '#eeeeee');
    addPoint(styleMap, 'power_source', 'coal', 'josm/misc/landmark/power/fossil.png');
    addArea(styleMap, 'power_source', 'coal', '#eeeeee');
    addPoint(styleMap, 'power_source', 'gas', 'josm/misc/landmark/power/fossil.png');
    addArea(styleMap, 'power_source', 'gas', '#eeeeee');
    addPoint(styleMap, 'power_source', 'photovoltaic', 'josm/misc/landmark/power/fossil.png');
    addArea(styleMap, 'power_source', 'photovoltaic', '#eeeeee');
    addPoint(styleMap, 'power_source', 'nuclear', 'josm/misc/landmark/power/nuclear.png');
    addArea(styleMap, 'power_source', 'nuclear', '#eeeeee');
    addPoint(styleMap, 'power', 'generator', 'josm/misc/landmark/power.png');
    addArea(styleMap, 'power', 'generator', '#eeeeee');
    addPoint(styleMap, 'man_made', 'beacon', 'josm/misc/landmark/beacon.png');
    addArea(styleMap, 'man_made', 'beacon', '#d8d8d8');
    addPoint(styleMap, 'man_made', 'crane', 'josm/misc/landmark/crane.png');
    addArea(styleMap, 'man_made', 'crane', '#d8d8d8');
    addPoint(styleMap, 'man_made', 'flagpole', 'josm/misc/flag.png');
    addArea(styleMap, 'man_made', 'flagpole', '#d8d8d8');
    addPoint(styleMap, 'man_made', 'gasometer', 'josm/misc/landmark/gasometer.png');
    addArea(styleMap, 'man_made', 'gasometer', '#d8d8d8');
    addPoint(styleMap, 'man_made', 'lighthouse', 'josm/misc/landmark/lighthouse.png');
    addArea(styleMap, 'man_made', 'lighthouse', '#d8d8d8');
    addPoint(styleMap, 'man_made', 'pier', 'josm/nautical/pier.png');
    addStrokeArea(styleMap, 'man_made', 'pier', '#660000', '2');
    addStroke(styleMap, 'man_made', 'pipeline', '#660000', 2);
    addPoint(styleMap, 'man_made', 'petroleum_well', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'man_made', 'reservoir_covered', 'josm/misc/landmark/reservoir_covered.png');
    addArea(styleMap, 'man_made', 'reservoir_covered', '#d8d8d8');
    addPoint(styleMap, 'man_made', 'surveillance', 'josm/misc/surveillance.png');
    addArea(styleMap, 'man_made', 'surveillance', '#d8d8d8');
    addPoint(styleMap, 'man_made', 'survey_point', 'josm/misc/landmark/survey_point.png');
    addArea(styleMap, 'man_made', 'survey_point', '#d8d8d8');
    addPoint(styleMap, 'man_made', 'tower', 'josm/misc/landmark/tower.png');
    addArea(styleMap, 'man_made', 'tower', '#d8d8d8');
    addPoint(styleMap, 'man_made', 'wastewater_plant', 'josm/misc/landmark/wastewater_plant.png');
    addArea(styleMap, 'man_made', 'wastewater_plant', '#d8d8d8');
    addPoint(styleMap, 'man_made', 'watermill', 'josm/misc/landmark/watermill.png');
    addArea(styleMap, 'man_made', 'watermill', '#d8d8d8');
    addPoint(styleMap, 'man_made', 'water_tower', 'josm/misc/landmark/water_tower.png');
    addArea(styleMap, 'man_made', 'water_tower', '#d8d8d8');
    addPoint(styleMap, 'man_made', 'windmill', 'josm/misc/landmark/windmill.png');
    addArea(styleMap, 'man_made', 'windmill', '#d8d8d8');
    addPoint(styleMap, 'man_made', 'works', 'josm/misc/landmark/works.png');
    addArea(styleMap, 'man_made', 'works', '#d8d8d8');
    addPoint(styleMap, 'man_made', 'water_works', 'josm/misc/no_icon.png');
    addArea(styleMap, 'man_made', 'water_works', '#d8d8d8');
    addPoint(styleMap, 'leisure', 'sports_centre', 'josm/sport/centre.png');
    addArea(styleMap, 'leisure', 'sports_centre', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'golf_course', 'josm/sport/golf.png');
    addArea(styleMap, 'leisure', 'golf_course', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'stadium', 'josm/sport/stadium.png');
    addArea(styleMap, 'leisure', 'stadium', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'track', 'josm/sport/track.png');
    addArea(styleMap, 'leisure', 'track', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'pitch', 'josm/sport/pitch.png');
    addArea(styleMap, 'leisure', 'pitch', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'water_park', 'josm/leisure/water_park.png');
    addArea(styleMap, 'leisure', 'water_park', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'marina', 'josm/nautical/marina.png');
    addArea(styleMap, 'leisure', 'marina', '#0070cf');
    addPoint(styleMap, 'leisure', 'slipway', 'josm/nautical/slipway.png');
    addArea(styleMap, 'leisure', 'slipway', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'fishing', 'josm/sport/fishing.png');
    addArea(styleMap, 'leisure', 'fishing', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'nature_reserve', 'josm/leisure/nature_reserve.png');
    addArea(styleMap, 'leisure', 'nature_reserve', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'park', 'josm/leisure/park.png');
    addArea(styleMap, 'leisure', 'park', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'playground', 'josm/leisure/playground.png');
    addArea(styleMap, 'leisure', 'playground', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'garden', 'josm/leisure/garden.png');
    addArea(styleMap, 'leisure', 'garden', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'common', 'josm/leisure/common.png');
    addArea(styleMap, 'leisure', 'common', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'swimming_pool', 'josm/sport/pool.png');
    addArea(styleMap, 'leisure', 'swimming_pool', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'miniature_golf', 'josm/sport/golf.png');
    addArea(styleMap, 'leisure', 'miniature_golf', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'dog_park', 'josm/leisure/dog.png');
    addArea(styleMap, 'leisure', 'dog_park', '#c7f1a3');
    addPoint(styleMap, 'leisure', 'ice_rink', 'josm/sport/hockey.png');
    addArea(styleMap, 'leisure', 'ice_rink', '#c7f1a3');
    addPoint(styleMap, 'amenity', 'pub', 'josm/food/pub.png');
    addArea(styleMap, 'amenity', 'pub', '#ecba52');
    addPoint(styleMap, 'amenity', 'biergarten', 'josm/food/biergarten.png');
    addArea(styleMap, 'amenity', 'biergarten', '#ecba52');
    addPoint(styleMap, 'amenity', 'nightclub', 'josm/leisure/nightclub.png');
    addArea(styleMap, 'amenity', 'nightclub', '#ecba52');
    addPoint(styleMap, 'amenity', 'stripclub', 'josm/leisure/stripclub.png');
    addArea(styleMap, 'amenity', 'stripclub', '#ecba52');
    addPoint(styleMap, 'amenity', 'brothel', 'josm/leisure/stripclub.png');
    addArea(styleMap, 'amenity', 'brothel', '#ecba52');
    addPoint(styleMap, 'amenity', 'cafe', 'josm/food/cafe.png');
    addArea(styleMap, 'amenity', 'cafe', '#ecba52');
    addPoint(styleMap, 'amenity', 'restaurant', 'josm/food/restaurant.png');
    addArea(styleMap, 'amenity', 'restaurant', '#ecba52');
    addPoint(styleMap, 'amenity', 'food_court', 'josm/food/restaurant.png');
    addArea(styleMap, 'amenity', 'food_court', '#ecba52');
    addPoint(styleMap, 'amenity', 'fast_food', 'josm/food/fastfood.png');
    addArea(styleMap, 'amenity', 'fast_food', '#ecba52');
    addPoint(styleMap, 'amenity', 'bar', 'josm/food/bar.png');
    addArea(styleMap, 'amenity', 'bar', '#ecba52');
    addPoint(styleMap, 'amenity', 'ice_cream', 'josm/food/icecream.png');
    addArea(styleMap, 'amenity', 'ice_cream', '#ecba52');
    addPoint(styleMap, 'parking', 'multi-storey', 'josm/vehicle/parking/multi-storey.png');
    addArea(styleMap, 'parking', 'multi-storey', '#f7efb7');
    addPoint(styleMap, 'parking', 'underground', 'josm/vehicle/parking/underground.png');
    addArea(styleMap, 'parking', 'underground', '#f7efb7');
    addPoint(styleMap, 'parking', 'park_and_ride', 'josm/vehicle/parking/park_ride.png');
    addArea(styleMap, 'parking', 'park_and_ride', '#f7efb7');
    addPoint(styleMap, 'parking', 'surface', 'josm/vehicle/parking.png');
    addArea(styleMap, 'parking', 'surface', '#f7efb7');
    addPoint(styleMap, 'amenity', 'parking', 'josm/vehicle/parking.png');
    addArea(styleMap, 'amenity', 'parking', '#f7efb7');
    addPoint(styleMap, 'amenity', 'bicycle_parking', 'josm/vehicle/parking/bicycle.png');
    addArea(styleMap, 'amenity', 'bicycle_parking', '#f7efb7');
    addPoint(styleMap, 'amenity', 'bicycle_rental', 'josm/vehicle/rental/bicycle.png');
    addArea(styleMap, 'amenity', 'bicycle_rental', '#f7efb7');
    addPoint(styleMap, 'amenity', 'car_rental', 'josm/vehicle/rental/car.png');
    addArea(styleMap, 'amenity', 'car_rental', '#f7efb7');
    addPoint(styleMap, 'amenity', 'car_sharing', 'josm/vehicle/car_sharing.png');
    addArea(styleMap, 'amenity', 'car_sharing', '#f7efb7');
    addPoint(styleMap, 'amenity', 'car_wash', 'josm/vehicle/car_wash.png');
    addArea(styleMap, 'amenity', 'car_wash', '#f7efb7');
    addPoint(styleMap, 'amenity', 'taxi', 'josm/transport/taxi.png');
    addArea(styleMap, 'amenity', 'taxi', '#f7efb7');
    addPoint(styleMap, 'amenity', 'fuel', 'josm/vehicle/fuel.png');
    addArea(styleMap, 'amenity', 'fuel', '#f7efb7');
    addPoint(styleMap, 'amenity', 'grit_bin', 'josm/misc/grit_bin.png');
    addPoint(styleMap, 'amenity', 'telephone', 'josm/service/telephone.png');
    addArea(styleMap, 'amenity', 'telephone', '#f7efb7');
    addPoint(styleMap, 'amenity', 'clock', 'josm/service/clock.png');
    addPoint(styleMap, 'amenity', 'emergency_phone', 'josm/vehicle/emergency_phone.png');
    addArea(styleMap, 'amenity', 'emergency_phone', '#f7efb7');
    addPoint(styleMap, 'amenity', 'toilets', 'josm/service/toilets.png');
    addArea(styleMap, 'amenity', 'toilets', '#f7efb7');
    addPoint(styleMap, 'amenity', 'recycling', 'josm/service/recycling.png');
    addArea(styleMap, 'amenity', 'recycling', '#f7efb7');
    addPoint(styleMap, 'amenity', 'waste_basket', 'josm/service/recycling/trash-bin.png');
    addPoint(styleMap, 'amenity', 'public_building', 'josm/service.png');
    addArea(styleMap, 'amenity', 'public_building', '#f7efb7');
    addPoint(styleMap, 'amenity', 'embassy', 'josm/service.png');
    addArea(styleMap, 'amenity', 'embassy', '#f7efb7');
    addPoint(styleMap, 'amenity', 'townhall', 'josm/service.png');
    addArea(styleMap, 'amenity', 'townhall', '#f7efb7');
    addPoint(styleMap, 'amenity', 'community_centre', 'josm/service.png');
    addArea(styleMap, 'amenity', 'community_centre', '#f7efb7');
    addPoint(styleMap, 'amenity', 'drinking_water', 'josm/food/drinking_water.png');
    addArea(styleMap, 'amenity', 'drinking_water', '#00005f');
    addPoint(styleMap, 'amenity', 'fountain', 'josm/misc/landmark/spring.png');
    addArea(styleMap, 'amenity', 'fountain', '#00005f');
    addPoint(styleMap, 'religion', 'bahai', 'josm/religion/bahai.png');
    addPoint(styleMap, 'religion', 'buddhist', 'josm/religion/buddhism.png');
    addPoint(styleMap, 'religion', 'christian', 'josm/religion/church.png');
    addPoint(styleMap, 'religion', 'hindu', 'josm/religion/hinduism.png');
    addPoint(styleMap, 'religion', 'jain', 'josm/religion/jainism.png');
    addPoint(styleMap, 'religion', 'jewish', 'josm/religion/jewish.png');
    addPoint(styleMap, 'religion', 'muslim', 'josm/religion/muslim.png');
    addPoint(styleMap, 'religion', 'sikh', 'josm/religion/sikhism.png');
    addPoint(styleMap, 'religion', 'shinto', 'josm/religion/shinto.png');
    addPoint(styleMap, 'religion', 'spiritualist', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'religion', 'taoist', 'josm/religion/taoism.png');
    addPoint(styleMap, 'religion', 'unitarian', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'religion', 'zoroastrian', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'amenity', 'place_of_worship', 'josm/religion.png');
    addArea(styleMap, 'amenity', 'place_of_worship', '#f7efb7');
    addPoint(styleMap, 'amenity', 'grave_yard', 'josm/rendering/landuse/cemetery.png');
    addArea(styleMap, 'amenity', 'grave_yard', '#f7efb7');
    addPoint(styleMap, 'amenity', 'crematorium', 'josm/misc/no_icon.png');
    addArea(styleMap, 'amenity', 'crematorium', '#f7efb7');
    addPoint(styleMap, 'amenity', 'post_office', 'josm/service/post_office.png');
    addArea(styleMap, 'amenity', 'post_office', '#f7efb7');
    addPoint(styleMap, 'amenity', 'post_box', 'josm/service/post_box.png');
    addArea(styleMap, 'amenity', 'post_box', '#f7efb7');
    addPoint(styleMap, 'amenity', 'school', 'josm/education/school.png');
    addArea(styleMap, 'amenity', 'school', '#f7efb7');
    addPoint(styleMap, 'amenity', 'university', 'josm/education/university.png');
    addArea(styleMap, 'amenity', 'university', '#f7efb7');
    addPoint(styleMap, 'amenity', 'college', 'josm/education/college.png');
    addArea(styleMap, 'amenity', 'college', '#f7efb7');
    addPoint(styleMap, 'amenity', 'kindergarten', 'josm/education/kindergarten.png');
    addArea(styleMap, 'amenity', 'kindergarten', '#f7efb7');
    addPoint(styleMap, 'amenity', 'driving_school', 'josm/education/driving_school.png');
    addArea(styleMap, 'amenity', 'driving_school', '#f7efb7');
    addPoint(styleMap, 'amenity', 'pharmacy', 'josm/health/pharmacy.png');
    addArea(styleMap, 'amenity', 'pharmacy', '#eeeeee');
    addPoint(styleMap, 'amenity', 'hospital', 'josm/health/hospital.png');
    addArea(styleMap, 'amenity', 'hospital', '#eeeeee');
    addPoint(styleMap, 'amenity', 'nursery', 'josm/misc/no_icon.png');
    addArea(styleMap, 'amenity', 'nursery', '#eeeeee');
    addPoint(styleMap, 'amenity', 'baby_hatch', 'josm/misc/no_icon.png');
    addArea(styleMap, 'amenity', 'baby_hatch', '#eeeeee');
    addPoint(styleMap, 'amenity', 'doctors', 'josm/health/doctor.png');
    addArea(styleMap, 'amenity', 'doctors', '#eeeeee');
    addPoint(styleMap, 'amenity', 'dentist', 'josm/health/dentist.png');
    addArea(styleMap, 'amenity', 'dentist', '#eeeeee');
    addPoint(styleMap, 'amenity', 'veterinary', 'josm/health/veterinary.png');
    addArea(styleMap, 'amenity', 'veterinary', '#eeeeee');
    addPoint(styleMap, 'amenity', 'library', 'josm/shop/rental/library.png');
    addArea(styleMap, 'amenity', 'library', '#f7efb7');
    addPoint(styleMap, 'amenity', 'police', 'josm/service/police.png');
    addArea(styleMap, 'amenity', 'police', '#f7efb7');
    addPoint(styleMap, 'amenity', 'fire_station', 'josm/service/firebrigade.png');
    addArea(styleMap, 'amenity', 'fire_station', '#f7efb7');
    addPoint(styleMap, 'amenity', 'bus_station', 'josm/transport/bus.png');
    addArea(styleMap, 'amenity', 'bus_station', '#f7efb7');
    addPoint(styleMap, 'amenity', 'ferry_terminal', 'josm/misc/no_icon.png');
    addArea(styleMap, 'amenity', 'ferry_terminal', '#f7efb7');
    addPoint(styleMap, 'amenity', 'theatre', 'josm/leisure/theater.png');
    addArea(styleMap, 'amenity', 'theatre', '#f7efb7');
    addPoint(styleMap, 'amenity', 'cinema', 'josm/leisure/cinema.png');
    addArea(styleMap, 'amenity', 'cinema', '#f7efb7');
    addPoint(styleMap, 'amenity', 'arts_centre', 'josm/service/arts_centre.png');
    addArea(styleMap, 'amenity', 'arts_centre', '#f7efb7');
    addPoint(styleMap, 'amenity', 'courthouse', 'josm/service/administration/court_of_law.png');
    addArea(styleMap, 'amenity', 'courthouse', '#f7efb7');
    addPoint(styleMap, 'amenity', 'prison', 'josm/service/administration/prison.png');
    addArea(styleMap, 'amenity', 'prison', '#f7efb7');
    addPoint(styleMap, 'amenity', 'bank', 'josm/money/bank.png');
    addArea(styleMap, 'amenity', 'bank', '#f7efb7');
    addPoint(styleMap, 'amenity', 'bureau_de_change', 'josm/money/exchange.png');
    addArea(styleMap, 'amenity', 'bureau_de_change', '#f7efb7');
    addPoint(styleMap, 'amenity', 'atm', 'josm/money/atm.png');
    addArea(styleMap, 'amenity', 'atm', '#f7efb7');
    addPoint(styleMap, 'amenity', 'bench', 'josm/leisure/bench.png');
    addArea(styleMap, 'amenity', 'bench', '#f7efb7');
    addPoint(styleMap, 'amenity', 'bbq', 'josm/leisure/bbq.png');
    addArea(styleMap, 'amenity', 'bbq', '#f7efb7');
    addPoint(styleMap, 'amenity', 'fire_hydrant', 'josm/service/fire_hydrant.png');
    addArea(styleMap, 'amenity', 'fire_hydrant', '#f7efb7');
    addPoint(styleMap, 'amenity', 'shelter', 'josm/accommodation/shelter.png');
    addArea(styleMap, 'amenity', 'shelter', '#f7efb7');
    addPoint(styleMap, 'amenity', 'hunting_stand', 'josm/hunting_stand.png');
    addArea(styleMap, 'amenity', 'hunting_stand', '#f7efb7');
    addPoint(styleMap, 'amenity', 'marketplace', 'josm/place/marketplace.png');
    addArea(styleMap, 'amenity', 'marketplace', '#f7efb7');
    addPoint(styleMap, 'amenity', 'wlan', 'josm/wlan.png');
    addArea(styleMap, 'amenity', 'wlan', '#f7efb7');
    addPoint(styleMap, 'vending', 'excrement_bags', 'josm/service/excrement_bags.png');
    addPoint(styleMap, 'amenity', 'vending_machine', 'josm/transport/ticket-machine.png');
    addArea(styleMap, 'amenity', 'vending_machine', '#f7efb7');
    addPoint(styleMap, 'shop', 'supermarket', 'josm/shop/supermarket.png');
    addArea(styleMap, 'shop', 'supermarket', '#00005f');
    addPoint(styleMap, 'shop', 'convenience', 'josm/shop/supermarket.png');
    addArea(styleMap, 'shop', 'convenience', '#00005f');
    addPoint(styleMap, 'shop', 'bakery', 'josm/shop/groceries/bakery.png');
    addArea(styleMap, 'shop', 'bakery', '#00005f');
    addPoint(styleMap, 'shop', 'butcher', 'josm/shop/groceries/butcher.png');
    addArea(styleMap, 'shop', 'butcher', '#00005f');
    addPoint(styleMap, 'shop', 'bicycle', 'josm/sport/bicycle.png');
    addArea(styleMap, 'shop', 'bicycle', '#00005f');
    addPoint(styleMap, 'shop', 'doityourself', 'josm/shop/diy_store.png');
    addArea(styleMap, 'shop', 'doityourself', '#00005f');
    addPoint(styleMap, 'shop', 'dry_cleaning', 'josm/shop/laundry.png');
    addArea(styleMap, 'shop', 'dry_cleaning', '#00005f');
    addPoint(styleMap, 'shop', 'laundry', 'josm/shop/laundry.png');
    addArea(styleMap, 'shop', 'laundry', '#00005f');
    addPoint(styleMap, 'shop', 'outdoor', 'josm/shop/sports/outdoor.png');
    addArea(styleMap, 'shop', 'outdoor', '#00005f');
    addPoint(styleMap, 'shop', 'kiosk', 'josm/shop/kiosk.png');
    addArea(styleMap, 'shop', 'kiosk', '#00005f');
    addPoint(styleMap, 'shop', 'alcohol', 'josm/shop/beverages.png');
    addArea(styleMap, 'shop', 'alcohol', '#00005f');
    addPoint(styleMap, 'shop', 'beverages', 'josm/shop/beverages.png');
    addArea(styleMap, 'shop', 'beverages', '#00005f');
    addPoint(styleMap, 'shop', 'books', 'josm/shop/rental/library.png');
    addArea(styleMap, 'shop', 'books', '#00005f');
    addPoint(styleMap, 'shop', 'car', 'josm/transport/car.png');
    addArea(styleMap, 'shop', 'car', '#00005f');
    addPoint(styleMap, 'shop', 'car_dealer', 'josm/transport/car.png');
    addArea(styleMap, 'shop', 'car_dealer', '#00005f');
    addPoint(styleMap, 'shop', 'car_repair', 'josm/transport/car.png');
    addArea(styleMap, 'shop', 'car_repair', '#00005f');
    addPoint(styleMap, 'shop', 'chemist', 'josm/shop/chemist.png');
    addArea(styleMap, 'shop', 'chemist', '#00005f');
    addPoint(styleMap, 'shop', 'clothes', 'josm/shop/clothes.png');
    addArea(styleMap, 'shop', 'clothes', '#00005f');
    addPoint(styleMap, 'shop', 'computer', 'josm/shop/computer.png');
    addArea(styleMap, 'shop', 'computer', '#00005f');
    addPoint(styleMap, 'shop', 'cycle_repair', 'josm/sport/bicycle.png');
    addArea(styleMap, 'shop', 'cycle_repair', '#00005f');
    addPoint(styleMap, 'shop', 'department_store', 'josm/shop/mall.png');
    addArea(styleMap, 'shop', 'department_store', '#00005f');
    addPoint(styleMap, 'shop', 'electronics', 'josm/shop/electronics.png');
    addArea(styleMap, 'shop', 'electronics', '#00005f');
    addPoint(styleMap, 'shop', 'furniture', 'josm/shop/furniture.png');
    addArea(styleMap, 'shop', 'furniture', '#00005f');
    addPoint(styleMap, 'shop', 'florist', 'josm/shop/florist.png');
    addArea(styleMap, 'shop', 'florist', '#00005f');
    addPoint(styleMap, 'shop', 'groceries', 'josm/shop/groceries/fruits.png');
    addArea(styleMap, 'shop', 'groceries', '#00005f');
    addPoint(styleMap, 'shop', 'garden_centre', 'josm/shop/garden_centre.png');
    addArea(styleMap, 'shop', 'garden_centre', '#00005f');
    addPoint(styleMap, 'shop', 'hairdresser', 'josm/shop/hairdresser.png');
    addArea(styleMap, 'shop', 'hairdresser', '#00005f');
    addPoint(styleMap, 'shop', 'hardware', 'josm/shop/diy_store.png');
    addArea(styleMap, 'shop', 'hardware', '#00005f');
    addPoint(styleMap, 'shop', 'hifi', 'josm/shop/hifi.png');
    addArea(styleMap, 'shop', 'hifi', '#00005f');
    addPoint(styleMap, 'shop', 'jewelry', 'josm/shop/jewelry.png');
    addArea(styleMap, 'shop', 'jewelry', '#00005f');
    addPoint(styleMap, 'shop', 'mall', 'josm/shop/mall.png');
    addArea(styleMap, 'shop', 'mall', '#00005f');
    addPoint(styleMap, 'shop', 'motorcycle', 'josm/vehicle/motorbike.png');
    addArea(styleMap, 'shop', 'motorcycle', '#00005f');
    addPoint(styleMap, 'shop', 'newsagent', 'josm/shop/kiosk.png');
    addArea(styleMap, 'shop', 'newsagent', '#00005f');
    addPoint(styleMap, 'shop', 'organic', 'josm/shop/groceries/fruits.png');
    addArea(styleMap, 'shop', 'organic', '#00005f');
    addPoint(styleMap, 'shop', 'optician', 'josm/shop/optician.png');
    addArea(styleMap, 'shop', 'optician', '#00005f');
    addPoint(styleMap, 'shop', 'shoes', 'josm/shop/shoes.png');
    addArea(styleMap, 'shop', 'shoes', '#00005f');
    addPoint(styleMap, 'shop', 'sports', 'josm/sport/multi.png');
    addArea(styleMap, 'shop', 'sports', '#00005f');
    addPoint(styleMap, 'shop', 'stationery', 'josm/misc/no_icon.png');
    addArea(styleMap, 'shop', 'stationery', '#00005f');
    addPoint(styleMap, 'shop', 'tailor', 'josm/shop/tailor.png');
    addArea(styleMap, 'shop', 'tailor', '#00005f');
    addPoint(styleMap, 'shop', 'travel_agency', 'josm/place/island.png');
    addArea(styleMap, 'shop', 'travel_agency', '#00005f');
    addPoint(styleMap, 'shop', 'toys', 'josm/shop/toys.png');
    addArea(styleMap, 'shop', 'toys', '#00005f');
    addPoint(styleMap, 'shop', 'video', 'josm/shop/video.png');
    addArea(styleMap, 'shop', 'video', '#00005f');
    addPoint(styleMap, 'shop', 'shopping_centre', 'josm/shop/mall.png');
    addArea(styleMap, 'shop', 'shopping_centre', '#00005f');
    addPoint(styleMap, 'tourism', 'hotel', 'josm/accommodation.png');
    addArea(styleMap, 'tourism', 'hotel', '#e1a0a2');
    addPoint(styleMap, 'tourism', 'motel', 'josm/accommodation/motel.png');
    addArea(styleMap, 'tourism', 'motel', '#e1a0a2');
    addPoint(styleMap, 'tourism', 'guest_house', 'josm/accommodation/guest_house.png');
    addArea(styleMap, 'tourism', 'guest_house', '#e1a0a2');
    addPoint(styleMap, 'tourism', 'hostel', 'josm/accommodation/hostel.png');
    addArea(styleMap, 'tourism', 'hostel', '#e1a0a2');
    addPoint(styleMap, 'tourism', 'chalet', 'josm/accommodation/chalet.png');
    addArea(styleMap, 'tourism', 'chalet', '#e1a0a2');
    addPoint(styleMap, 'tourism', 'alpine_hut', 'josm/accommodation/alpine_hut.png');
    addArea(styleMap, 'tourism', 'alpine_hut', '#e1a0a2');
    addPoint(styleMap, 'tourism', 'camp_site', 'josm/accommodation/camping.png');
    addArea(styleMap, 'tourism', 'camp_site', '#e1a0a2');
    addPoint(styleMap, 'tourism', 'caravan_site', 'josm/accommodation/camping/caravan.png');
    addArea(styleMap, 'tourism', 'caravan_site', '#e1a0a2');
    addPoint(styleMap, 'tourism', 'picnic_site', 'josm/leisure/picnic.png');
    addArea(styleMap, 'tourism', 'picnic_site', '#e180a2');
    addPoint(styleMap, 'tourism', 'viewpoint', 'josm/sightseeing/viewpoint.png');
    addArea(styleMap, 'tourism', 'viewpoint', '#e180a2');
    addPoint(styleMap, 'tourism', 'theme_park', 'josm/leisure/theme_park.png');
    addArea(styleMap, 'tourism', 'theme_park', '#e180a2');
    addPoint(styleMap, 'tourism', 'attraction', 'josm/sightseeing.png');
    addArea(styleMap, 'tourism', 'attraction', '#e180a2');
    addPoint(styleMap, 'tourism', 'zoo', 'josm/leisure/zoo.png');
    addArea(styleMap, 'tourism', 'zoo', '#e180a2');
    addPoint(styleMap, 'tourism', 'artwork', 'josm/service/arts_centre.png');
    addStrokeArea(styleMap, 'tourism', 'artwork', '#e180a2', '2');
    addPoint(styleMap, 'tourism', 'museum', 'josm/sightseeing/museum.png');
    addArea(styleMap, 'tourism', 'museum', '#e180a2');
    addPoint(styleMap, 'information', 'guidepost', 'josm/misc/information/guidepost.png');
    addPoint(styleMap, 'information', 'office', 'josm/misc/information/informationoffice.png');
    addArea(styleMap, 'information', 'office', '#e180a2');
    addPoint(styleMap, 'information', 'map', 'josm/misc/information/map.png');
    addPoint(styleMap, 'information', 'board', 'josm/misc/information/board.png');
    addPoint(styleMap, 'tourism', 'information', 'josm/misc/information.png');
    addArea(styleMap, 'tourism', 'information', '#e180a2');
    addPoint(styleMap, 'historic', 'castle', 'josm/sightseeing/castle.png');
    addArea(styleMap, 'historic', 'castle', '#663300');
    addPoint(styleMap, 'historic', 'monument', 'josm/sightseeing/monument.png');
    addArea(styleMap, 'historic', 'monument', '#663300');
    addPoint(styleMap, 'historic', 'memorial', 'josm/sightseeing/memorial.png');
    addArea(styleMap, 'historic', 'memorial', '#663300');
    addPoint(styleMap, 'historic', 'archaeological_site', 'josm/sightseeing/archaeological.png');
    addArea(styleMap, 'historic', 'archaeological_site', '#663300');
    addPoint(styleMap, 'historic', 'ruins', 'josm/sightseeing/ruins.png');
    addArea(styleMap, 'historic', 'ruins', '#663300');
    addPoint(styleMap, 'historic', 'battlefield', 'josm/sightseeing/battlefield.png');
    addArea(styleMap, 'historic', 'battlefield', '#663300');
    addPoint(styleMap, 'geological', 'palaeontological_site', 'josm/historic/palaeontological_site.png');
    addArea(styleMap, 'geological', 'palaeontological_site', '#663300');
    addPoint(styleMap, 'historic', 'wayside_cross', 'josm/religion/wayside_cross.png');
    addArea(styleMap, 'historic', 'wayside_cross', '#663300');
    addPoint(styleMap, 'historic', 'wayside_shrine', 'josm/religion/wayside_shrine.png');
    addArea(styleMap, 'historic', 'wayside_shrine', '#663300');
    addPoint(styleMap, 'historic', 'boundary_stone', 'josm/historic/boundary_stone.png');
    addArea(styleMap, 'historic', 'boundary_stone', '#663300');
    addPoint(styleMap, 'landuse', 'farm', 'josm/misc/landmark/farm.png');
    addArea(styleMap, 'landuse', 'farm', '#b1e0c2');
    addPoint(styleMap, 'landuse', 'farmland', 'josm/misc/no_icon.png');
    addArea(styleMap, 'landuse', 'farmland', '#b1e0c2');
    addPoint(styleMap, 'landuse', 'meadow', 'josm/misc/no_icon.png');
    addArea(styleMap, 'landuse', 'meadow', '#b1e0c2');
    addPoint(styleMap, 'landuse', 'vineyard', 'josm/shop/groceries/fruits.png');
    addArea(styleMap, 'landuse', 'vineyard', '#b1e0c2');
    addArea(styleMap, 'landuse', 'orchard', '#b1e0c2');
    addPoint(styleMap, 'landuse', 'quarry', 'josm/misc/landmark/mine.png');
    addArea(styleMap, 'landuse', 'quarry', '#888888');
    addPoint(styleMap, 'landuse', 'landfill', 'josm/misc/no_icon.png');
    addArea(styleMap, 'landuse', 'landfill', '#663300');
    addPoint(styleMap, 'landuse', 'basin', 'josm/misc/no_icon.png');
    addArea(styleMap, 'landuse', 'basin', '#0000bf');
    addPoint(styleMap, 'landuse', 'reservoir', 'josm/misc/no_icon.png');
    addArea(styleMap, 'landuse', 'reservoir', '#0000bf');
    addPoint(styleMap, 'landuse', 'forest', 'josm/misc/landmark/trees.png');
    addArea(styleMap, 'landuse', 'forest', '#b1efc8');
    addPoint(styleMap, 'landuse', 'allotments', 'josm/misc/landmark/plant.png');
    addArea(styleMap, 'landuse', 'allotments', '#b1e0c2');
    addPoint(styleMap, 'landuse', 'grass', 'josm/misc/landmark/plant.png');
    addArea(styleMap, 'landuse', 'grass', '#b1e0c2');
    addPoint(styleMap, 'landuse', 'residential', 'josm/misc/landuse/residential.png');
    addArea(styleMap, 'landuse', 'residential', '#f0f0f0');
    addPoint(styleMap, 'landuse', 'farmyard', 'josm/misc/no_icon.png');
    addArea(styleMap, 'landuse', 'farmyard', '#f0f0f0');
    addPoint(styleMap, 'landuse', 'retail', 'josm/shop/mall.png');
    addArea(styleMap, 'landuse', 'retail', '#dbdbdb');
    addPoint(styleMap, 'landuse', 'commercial', 'josm/misc/landuse/commercial.png');
    addArea(styleMap, 'landuse', 'commercial', '#dbdbdb');
    addPoint(styleMap, 'landuse', 'industrial', 'josm/misc/landmark/works.png');
    addArea(styleMap, 'landuse', 'industrial', '#ecd8ff');
    addPoint(styleMap, 'landuse', 'brownfield', 'josm/misc/no_icon.png');
    addArea(styleMap, 'landuse', 'brownfield', '#ecba32');
    addPoint(styleMap, 'landuse', 'greenfield', 'josm/misc/no_icon.png');
    addArea(styleMap, 'landuse', 'greenfield', '#b1ec5c');
    addPoint(styleMap, 'landuse', 'railway', 'josm/transport/railway_station.png');
    addArea(styleMap, 'landuse', 'railway', '#888888');
    addPoint(styleMap, 'landuse', 'construction', 'josm/misc/construction.png');
    addStrokeArea(styleMap, 'landuse', 'construction', '#ffff00', '1');
    addPoint(styleMap, 'landuse', 'military', 'josm/vehicle/tank.png');
    addArea(styleMap, 'landuse', 'military', '#b62c2c');
    addPoint(styleMap, 'landuse', 'cemetery', 'josm/rendering/landuse/cemetery.png');
    addArea(styleMap, 'landuse', 'cemetery', '#b1efc8');
    addPoint(styleMap, 'landuse', 'village_green', 'josm/leisure/common.png');
    addArea(styleMap, 'landuse', 'village_green', '#b1e0c2');
    addPoint(styleMap, 'landuse', 'recreation_ground', 'josm/leisure/common.png');
    addArea(styleMap, 'landuse', 'recreation_ground', '#b1e0c2');
    addPoint(styleMap, 'military', 'airfield', 'josm/transport/airport/airfield.png');
    addArea(styleMap, 'military', 'airfield', '#b62c2c');
    addPoint(styleMap, 'military', 'bunker', 'josm/misc/landmark/bunker.png');
    addArea(styleMap, 'military', 'bunker', '#b62c2c');
    addPoint(styleMap, 'military', 'barracks', 'josm/misc/no_icon.png');
    addArea(styleMap, 'military', 'barracks', '#b62c2c');
    addPoint(styleMap, 'military', 'danger_area', 'josm/misc/danger.png');
    addArea(styleMap, 'military', 'danger_area', '#b62c2c');
    addPoint(styleMap, 'military', 'range', 'josm/misc/landmark/range.png');
    addArea(styleMap, 'military', 'range', '#b62c2c');
    addPoint(styleMap, 'natural', 'spring', 'josm/misc/landmark/spring.png');
    addArea(styleMap, 'natural', 'spring', '#00005f');
    addPoint(styleMap, 'natural', 'peak', 'josm/misc/landmark/peak_small.png');
    addArea(styleMap, 'natural', 'peak', '#663300');
    addPoint(styleMap, 'natural', 'glacier', 'josm/misc/landmark/glacier_small.png');
    addArea(styleMap, 'natural', 'glacier', '#ffffff');
    addPoint(styleMap, 'natural', 'volcano', 'josm/misc/landmark/volcano_small.png');
    addArea(styleMap, 'natural', 'volcano', '#5f0000');
    addPoint(styleMap, 'natural', 'cliff', 'josm/misc/no_icon.png');
    addStrokeArea(styleMap, 'natural', 'cliff', '#002f00', '2');
    addPoint(styleMap, 'natural', 'scree', 'josm/misc/no_icon.png');
    addArea(styleMap, 'natural', 'scree', '#002f00');
    addPoint(styleMap, 'natural', 'scrub', 'josm/misc/no_icon.png');
    addArea(styleMap, 'natural', 'scrub', '#007000');
    addPoint(styleMap, 'natural', 'fell', 'josm/misc/no_icon.png');
    addArea(styleMap, 'natural', 'fell', '#002f00');
    addPoint(styleMap, 'natural', 'heath', 'josm/misc/no_icon.png');
    addArea(styleMap, 'natural', 'heath', '#ffffc0');
    addPoint(styleMap, 'natural', 'wood', 'josm/misc/landmark/trees.png');
    addArea(styleMap, 'natural', 'wood', '#008000');
    addPoint(styleMap, 'natural', 'wetland', 'josm/misc/no_icon.png');
    addArea(styleMap, 'natural', 'wetland', '#4f4ff3');
    addPoint(styleMap, 'natural', 'water', 'josm/nautical/water.png');
    addArea(styleMap, 'natural', 'water', '#0000ff');
    addPoint(styleMap, 'natural', 'coastline', 'josm/misc/no_icon.png');
    addStroke(styleMap, 'natural', 'coastline', '#0000ff', 1);
    addPoint(styleMap, 'natural', 'mud', 'josm/misc/no_icon.png');
    addArea(styleMap, 'natural', 'mud', '#cba762');
    addPoint(styleMap, 'natural', 'beach', 'josm/misc/no_icon.png');
    addArea(styleMap, 'natural', 'beach', '#f8dba2');
    addPoint(styleMap, 'natural', 'bay', 'josm/misc/no_icon.png');
    addArea(styleMap, 'natural', 'bay', '#002f00');
    addPoint(styleMap, 'natural', 'land', 'josm/misc/no_icon.png');
    addArea(styleMap, 'natural', 'land', '#002f00');
    addPoint(styleMap, 'natural', 'cave_entrance', 'josm/misc/no_icon.png');
    addArea(styleMap, 'natural', 'cave_entrance', '#002f00');
    addPoint(styleMap, 'natural', 'tree', 'josm/misc/landmark/trees.png');
    addStroke(styleMap, 'route', 'bus', '#809bc0', 1, 'dash');
    addStroke(styleMap, 'route', 'ferry', '#809bc0', 1, 'dash');
    addStroke(styleMap, 'route', 'flight', '#809bc0', 1, 'dash');
    addStroke(styleMap, 'route', 'ncn', '#809bc0', 1, 'dash');
    addStroke(styleMap, 'route', 'subsea', '#809bc0', 1, 'dash');
    addStroke(styleMap, 'route', 'ski', '#809bc0', 1, 'dash');
    addStroke(styleMap, 'route', 'tour', '#809bc0', 1, 'dash');
    addStroke(styleMap, 'route', 'pub_crawl', '#809bc0', 1, 'dash');
    addStroke(styleMap, 'boundary', 'national', '#FF6600', 1, 'dash');
    addStroke(styleMap, 'admin_level', '1', '#FF6600', 5, 'dash');
    addStroke(styleMap, 'admin_level', '2', '#FF6600', 5, 'dash');
    addStroke(styleMap, 'admin_level', '3', '#FF6600', 4, 'dash');
    addStroke(styleMap, 'admin_level', '4', '#FF6600', 4, 'dash');
    addStroke(styleMap, 'admin_level', '5', '#FF6600', 3, 'dash');
    addStroke(styleMap, 'admin_level', '6', '#FF6600', 3, 'dash');
    addStroke(styleMap, 'admin_level', '7', '#FF6600', 2, 'dash');
    addStroke(styleMap, 'admin_level', '8', '#FF6600', 2, 'dash');
    addStroke(styleMap, 'admin_level', '9', '#FF6600', 1, 'dash');
    addStroke(styleMap, 'admin_level', '10', '#FF6600', 1, 'dash');
    addStroke(styleMap, 'boundary', 'administrative', '#FF6600', 1, 'dash');
    addStroke(styleMap, 'boundary', 'civil', '#FF6600', 1, 'dash');
    addStroke(styleMap, 'boundary', 'political', '#FF6600', 1, 'dash');
    addStroke(styleMap, 'boundary', 'national_park', '#FF6600', 1, 'dash');
    addPoint(styleMap, 'sport', '9pin', 'josm/sport/10pin.png');
    addArea(styleMap, 'sport', '9pin', '#bde3cb');
    addPoint(styleMap, 'sport', '10pin', 'josm/sport/10pin.png');
    addArea(styleMap, 'sport', '10pin', '#bde3cb');
    addPoint(styleMap, 'sport', 'athletics', 'josm/misc/no_icon.png');
    addArea(styleMap, 'sport', 'athletics', '#bde3cb');
    addPoint(styleMap, 'sport', 'soccer', 'josm/sport/soccer.png');
    addArea(styleMap, 'sport', 'soccer', '#bde3cb');
    addPoint(styleMap, 'sport', 'australian_football', 'josm/sport/soccer.png');
    addArea(styleMap, 'sport', 'australian_football', '#bde3cb');
    addPoint(styleMap, 'sport', 'american_football', 'josm/sport/soccer.png');
    addArea(styleMap, 'sport', 'american_football', '#bde3cb');
    addPoint(styleMap, 'sport', 'canadian_football', 'josm/sport/soccer.png');
    addArea(styleMap, 'sport', 'canadian_football', '#bde3cb');
    addPoint(styleMap, 'sport', 'gaelic_football', 'josm/sport/soccer.png');
    addArea(styleMap, 'sport', 'gaelic_football', '#bde3cb');
    addPoint(styleMap, 'sport', 'rugby_league', 'josm/sport/football.png');
    addArea(styleMap, 'sport', 'rugby_league', '#bde3cb');
    addPoint(styleMap, 'sport', 'rugby_union', 'josm/sport/football.png');
    addArea(styleMap, 'sport', 'rugby_union', '#bde3cb');
    addPoint(styleMap, 'sport', 'baseball', 'josm/sport/baseball.png');
    addArea(styleMap, 'sport', 'baseball', '#bde3cb');
    addPoint(styleMap, 'sport', 'basketball', 'josm/sport/basketball.png');
    addArea(styleMap, 'sport', 'basketball', '#bde3cb');
    addPoint(styleMap, 'sport', 'boules', 'josm/sport/boule.png');
    addArea(styleMap, 'sport', 'boules', '#bde3cb');
    addPoint(styleMap, 'sport', 'bowls', 'josm/sport/boule.png');
    addArea(styleMap, 'sport', 'bowls', '#bde3cb');
    addPoint(styleMap, 'sport', 'canoe', 'josm/sport/canoe.png');
    addArea(styleMap, 'sport', 'canoe', '#bde3cb');
    addPoint(styleMap, 'sport', 'chess', 'josm/sport/chess.png');
    addArea(styleMap, 'sport', 'chess', '#bde3cb');
    addPoint(styleMap, 'sport', 'climbing', 'josm/sport/climbing.png');
    addArea(styleMap, 'sport', 'climbing', '#bde3cb');
    addPoint(styleMap, 'sport', 'cricket', 'josm/sport/cricket.png');
    addArea(styleMap, 'sport', 'cricket', '#bde3cb');
    addPoint(styleMap, 'sport', 'cricket_nets', 'josm/misc/no_icon.png');
    addArea(styleMap, 'sport', 'cricket_nets', '#bde3cb');
    addPoint(styleMap, 'sport', 'croquet', 'josm/sport/croquet.png');
    addArea(styleMap, 'sport', 'croquet', '#bde3cb');
    addPoint(styleMap, 'sport', 'cycling', 'josm/sport/cycling.png');
    addArea(styleMap, 'sport', 'cycling', '#bde3cb');
    addPoint(styleMap, 'sport', 'dog_racing', 'josm/leisure/dog.png');
    addArea(styleMap, 'sport', 'dog_racing', '#bde3cb');
    addPoint(styleMap, 'sport', 'equestrian', 'josm/sport/riding.png');
    addArea(styleMap, 'sport', 'equestrian', '#bde3cb');
    addPoint(styleMap, 'sport', 'golf', 'josm/sport/golf.png');
    addArea(styleMap, 'sport', 'golf', '#bde3cb');
    addPoint(styleMap, 'sport', 'gymnastics', 'josm/sport/multi.png');
    addArea(styleMap, 'sport', 'gymnastics', '#bde3cb');
    addPoint(styleMap, 'sport', 'hockey', 'josm/sport/hockey.png');
    addArea(styleMap, 'sport', 'hockey', '#bde3cb');
    addPoint(styleMap, 'sport', 'horse_racing', 'josm/sport/riding.png');
    addArea(styleMap, 'sport', 'horse_racing', '#bde3cb');
    addPoint(styleMap, 'sport', 'motor', 'josm/vehicle/motorbike.png');
    addArea(styleMap, 'sport', 'motor', '#bde3cb');
    addPoint(styleMap, 'sport', 'multi', 'josm/sport/multi.png');
    addArea(styleMap, 'sport', 'multi', '#bde3cb');
    addPoint(styleMap, 'sport', 'pelota', 'josm/misc/no_icon.png');
    addArea(styleMap, 'sport', 'pelota', '#bde3cb');
    addPoint(styleMap, 'sport', 'racquet', 'josm/sport/racquetball.png');
    addArea(styleMap, 'sport', 'racquet', '#bde3cb');
    addPoint(styleMap, 'sport', 'skating', 'josm/misc/no_icon.png');
    addArea(styleMap, 'sport', 'skating', '#bde3cb');
    addPoint(styleMap, 'sport', 'skateboard', 'josm/sport/skateboard.png');
    addArea(styleMap, 'sport', 'skateboard', '#bde3cb');
    addPoint(styleMap, 'sport', 'swimming', 'josm/sport/pool.png');
    addArea(styleMap, 'sport', 'swimming', '#bde3cb');
    addPoint(styleMap, 'sport', 'skiing', 'josm/sport/skiing.png');
    addArea(styleMap, 'sport', 'skiing', '#bde3cb');
    addPoint(styleMap, 'sport', 'table_tennis', 'josm/sport/table_tennis.png');
    addArea(styleMap, 'sport', 'table_tennis', '#bde3cb');
    addPoint(styleMap, 'sport', 'tennis', 'josm/sport/tennis.png');
    addArea(styleMap, 'sport', 'tennis', '#bde3cb');
    addPoint(styleMap, 'sport', 'paintball', 'josm/misc/no_icon.png');
    addArea(styleMap, 'sport', 'paintball', '#bde3cb');
    addPoint(styleMap, 'sport', 'squash', 'josm/misc/no_icon.png');
    addArea(styleMap, 'sport', 'squash', '#bde3cb');
    addPoint(styleMap, 'sport', 'shooting', 'josm/misc/no_icon.png');
    addArea(styleMap, 'sport', 'shooting', '#bde3cb');
    addPoint(styleMap, 'sport', 'volleyball', 'josm/sport/volleyball.png');
    addArea(styleMap, 'sport', 'volleyball', '#bde3cb');
    addPoint(styleMap, 'sport', 'beachvolleyball', 'josm/sport/volleyball.png');
    addArea(styleMap, 'sport', 'beachvolleyball', '#bde3cb');
    addPoint(styleMap, 'sport', 'bowling', 'josm/sport/10pin.png');
    addArea(styleMap, 'sport', 'bowling', '#bde3cb');
    addPoint(styleMap, 'sport', 'handball', 'josm/sport/handball.png');
    addArea(styleMap, 'sport', 'handball', '#bde3cb');
    addPoint(styleMap, 'sport', 'rowing', 'josm/sport/rowing.png');
    addArea(styleMap, 'sport', 'rowing', '#bde3cb');
    addPoint(styleMap, 'sport', 'sailing', 'josm/misc/no_icon.png');
    addArea(styleMap, 'sport', 'sailing', '#bde3cb');
    addPoint(styleMap, 'sport', 'diving', 'josm/sport/diving.png');
    addArea(styleMap, 'sport', 'diving', '#bde3cb');
    addPoint(styleMap, 'sport', 'badminton', 'josm/misc/no_icon.png');
    addArea(styleMap, 'sport', 'badminton', '#bde3cb');
    addPoint(styleMap, 'sport', 'archery', 'josm/sport/archery.png');
    addArea(styleMap, 'sport', 'archery', '#bde3cb');
    addPoint(styleMap, 'sport', 'fishing', 'josm/sport/fishing.png');
    addArea(styleMap, 'sport', 'fishing', '#bde3cb');
    addPoint(styleMap, 'mountain_pass', '.+', 'josm/misc/landmark/mountain_pass.png');
    addStroke(styleMap, 'mountain_pass', '.+', '#ff0000', 2, 'dash');
    addPoint(styleMap, 'place', 'continent', 'josm/place/settlement/capital.png');
    addArea(styleMap, 'place', 'continent', '#8de3cb');
    addPoint(styleMap, 'place', 'country', 'josm/place/settlement/capital.png');
    addArea(styleMap, 'place', 'country', '#8de3cb');
    addPoint(styleMap, 'place', 'state', 'josm/place/settlement/capital.png');
    addArea(styleMap, 'place', 'state', '#8de3cb');
    addPoint(styleMap, 'place', 'region', 'josm/place/settlement/capital.png');
    addArea(styleMap, 'place', 'region', '#8de3cb');
    addPoint(styleMap, 'place', 'county', 'josm/place/settlement/capital.png');
    addArea(styleMap, 'place', 'county', '#8de3cb');
    addPoint(styleMap, 'place', 'city', 'josm/place/settlement/city.png');
    addArea(styleMap, 'place', 'city', '#8de3cb');
    addPoint(styleMap, 'place', 'town', 'josm/place/settlement/town.png');
    addArea(styleMap, 'place', 'town', '#8de3cb');
    addPoint(styleMap, 'place', 'village', 'josm/place/settlement/town.png');
    addArea(styleMap, 'place', 'village', '#8de3cb');
    addPoint(styleMap, 'place', 'hamlet', 'josm/place/settlement/town.png');
    addArea(styleMap, 'place', 'hamlet', '#8de3cb');
    addPoint(styleMap, 'place', 'suburb', 'josm/place/settlement/town.png');
    addArea(styleMap, 'place', 'suburb', '#8de3cb');
    addPoint(styleMap, 'place', 'locality', 'josm/place/locality.png');
    addArea(styleMap, 'place', 'locality', '#8de3cb');
    addPoint(styleMap, 'place', 'island', 'josm/place/island.png');
    addArea(styleMap, 'place', 'island', '#8de3cb');
    addPoint(styleMap, 'place', 'islet', 'josm/place/islet.png');
    addArea(styleMap, 'place', 'islet', '#8de3cb');
    addPoint(styleMap, 'openGeoDB:type', 'Stadt', 'josm/place/settlement/town.png');
    addPoint(styleMap, 'openGeoDB:type', 'Kreis', 'josm/place/settlement/town.png');
    addPoint(styleMap, 'openGeoDB:type', 'Gemeinde', 'josm/place/settlement/town.png');
    addPoint(styleMap, 'openGeoDB:type', 'Ort', 'josm/place/settlement/town.png');
    addPoint(styleMap, 'openGeoDB:type', 'District', 'josm/place/settlement/town.png');
    addPoint(styleMap, 'openGeoDB:location', 'locality', 'josm/place/settlement/town.png');
    addPoint(styleMap, 'building', '.+', 'josm/misc/landmark/building.png');
    addArea(styleMap, 'building', '.+', '#cb9999');
    addArea(styleMap, 'area', '.+', '#ffffff');
    addPoint(styleMap, 'addr:housenumber', '.+', 'josm/misc/housenumber.png');
    addPoint(styleMap, 'addr:postcode', '.+', 'josm/misc/housenumber.png');
    addStroke(styleMap, 'addr:interpolation', 'odd', '#1C86EE', 1, 'dash');
    addStroke(styleMap, 'addr:interpolation', 'even', '#1C86EE', 1, 'dash');
    addStroke(styleMap, 'addr:interpolation', 'all', '#1C86EE', 1, 'dash');
    addStroke(styleMap, 'addr:interpolation', 'alphabetic', '#1C86EE', 1, 'dash');
    addPoint(styleMap, 'public_transport', 'stop_position', 'josm/misc/no_icon.png');
    addPoint(styleMap, 'public_transport', 'platform', 'josm/misc/no_icon.png');
    addStroke(styleMap, 'public_transport', 'platform', '#809bc0', 1, 'dash');

    return styleMap;
}
