#! /bin/bash

if [ ! -e up ] 
then
    mkdir up
    ln -s ../Export/index.html up
    ln -s ../Export/style.css up
    ln -s ../Export/josm up
    ln -s ../Export/symbols up
    ln -s ../Export/images up
    ln -s ../Export/img up
    ln -s ../Export/theme up
    ln -s ../Export/black.png up
    ln -s ../Export/white.png up
    ln -s ../Export/class_http.php up
    ln -s ../Export/proxy.php up
    ln -s ../Export/trace.html up
    ln -s ../Export/SportLaMargelle.osm up
fi
jsbuild $* jsbuild/app.cfg 
mv fr.js en.js app.js trace.js up
