#!/bin/bash

#ionice -c3 nice -n 19 rsync -av --delete-excluded --exclude="**/\.bzr/*" --exclude="**~" --exclude="**\.bak" --exclude="**/\.Trash*" --delete --stats --progress /media/Big /media/Public/Big;
ionice -c3 nice -n 19 rsync -av --delete-excluded --delete --stats --progress /media/Big /media/Public/Big;

touch /media/Public/Big;

